// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build scaletail_legacy_webclient

package buildfeatures

// HasWebClient is whether the binary was built with support for modular feature "Web client support".
// Specifically, it's whether the binary was built with the "scaletail_legacy_webclient" build tag.
// It's a const so it can be used for dead code elimination.
const HasWebClient = true
