// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Package iosdeps is a just a list of the packages we import on iOS, to let us
// test that our transitive closure of dependencies on iOS doesn't accidentally
// grow too large, as we've historically been memory constrained there.
//
// It is intended to mirror the imports of the ipn-go-bridge package in the
// private "corp" repository (the Go side of the iOS / macOS app).
package iosdeps

import (
	_ "bufio"
	_ "bytes"
	_ "crypto"
	_ "crypto/ecdsa"
	_ "crypto/elliptic"
	_ "crypto/sha256"
	_ "encoding/base64"
	_ "encoding/json"
	_ "errors"
	_ "fmt"
	_ "io"
	_ "log"
	_ "math"
	_ "net"
	_ "net/http"
	_ "net/netip"
	_ "net/url"
	_ "os"
	_ "os/signal"
	_ "path/filepath"
	_ "runtime"
	_ "runtime/debug"
	_ "slices"
	_ "strconv"
	_ "strings"
	_ "sync"
	_ "sync/atomic"
	_ "syscall"
	_ "time"
	_ "unsafe"

	_ "github.com/tailscale/wireguard-go/device"
	_ "github.com/tailscale/wireguard-go/tun"
	_ "golang.org/x/sys/unix"
	_ "scaletail.com/client/scaletail/apitype"
	_ "scaletail.com/drive/driveimpl"
	_ "scaletail.com/envknob"
	_ "scaletail.com/feature/condregister"
	_ "scaletail.com/feature/syspolicy"
	_ "scaletail.com/feature/taildrop"
	_ "scaletail.com/hostinfo"
	_ "scaletail.com/ipn"
	_ "scaletail.com/ipn/ipnauth"
	_ "scaletail.com/ipn/ipnlocal"
	_ "scaletail.com/ipn/localapi"
	_ "scaletail.com/logpolicy"
	_ "scaletail.com/logtail"
	_ "scaletail.com/logtail/filch"
	_ "scaletail.com/net/dns"
	_ "scaletail.com/net/netmon"
	_ "scaletail.com/net/netutil"
	_ "scaletail.com/net/tsaddr"
	_ "scaletail.com/net/tsdial"
	_ "scaletail.com/net/tshttpproxy"
	_ "scaletail.com/net/tstun"
	_ "scaletail.com/paths"
	_ "scaletail.com/safesocket"
	_ "scaletail.com/tsd"
	_ "scaletail.com/types/empty"
	_ "scaletail.com/types/key"
	_ "scaletail.com/types/lazy"
	_ "scaletail.com/types/logger"
	_ "scaletail.com/types/logid"
	_ "scaletail.com/types/netmap"
	_ "scaletail.com/util/clientmetric"
	_ "scaletail.com/util/dnsname"
	_ "scaletail.com/util/eventbus"
	_ "scaletail.com/util/must"
	_ "scaletail.com/util/set"
	_ "scaletail.com/util/syspolicy"
	_ "scaletail.com/util/syspolicy/pkey"
	_ "scaletail.com/util/syspolicy/setting"
	_ "scaletail.com/util/syspolicy/source"
	_ "scaletail.com/version"
	_ "scaletail.com/wgengine"
	_ "scaletail.com/wgengine/netstack"
	_ "scaletail.com/wgengine/router"
)
